# Generated by Django 2.2.1 on 2019-06-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='receiverAddressID',
            field=models.CharField(default='None', max_length=5),
        ),
    ]
